
- name: Deploy httpd on container
  hosts: all
  become: true
  gather_facts: false
  vars:
    webroot: "/webroot/"
  tasks:
    - name: Verify packages
      ansible.builtin.apt:
        name:
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Docker module
      ansible.builtin.pip:
        name: docker
    
    - name: Pull Docker image
      ansible.builtin.docker_image:
        name: httpd
        source: pull
        tag: latest

    - name: Webroot preset
      ansible.builtin.file:
        path: '{{ webroot }}'
        state: directory

    - name: Custom index.html
      ansible.builtin.copy:
        dest: '{{ webroot }}index.html'
        content: | 
          Custom Web Page

    - name: Run httpd container
      ansible.builtin.docker_container:
        name: webserver
        image: httpd
        state: started
        detach: true
        exposed_ports:
          - 80
        ports:
          - 8081:80
        volumes:
          - "{{ webroot }}:/usr/local/apache2/ntdocs"