# Ansible recipe for rebooting remotes
- name: reboot
  hosts: all
  become: true
  tasks:
    - name: reboot host
      ansible.builtin.reboot:
        msg: "Reboot started by Main Server"
        pre_reboot_delay: 15
        post_reboot_delay: 25
        test_command: "whoami"